version: '3.8'

services:
  stream-recorder:
    image: mandarin3d/stream-recorder:latest
    ports:
      - '3000:3000'
    volumes:
      - ./recordings:/usr/src/app/recordings
      - ./data:/usr/src/app/data
      - ./config.json:/usr/src/app/config.json
    environment:
      - JWT_SECRET=your-secure-jwt-secret-change-in-production
      - NODE_ENV=production
    restart: unless-stopped
    # Uncomment the following lines for resource limits in production
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 2G
    #     reservations:
    #       cpus: '1'
    #       memory: 1G
